source 'https://rubygems.org'

gem "thin", "~>1.6.1"
gem "sinatra", "~>1.4.3"
gem "haml"
gem "httpclient"
gem 'json'
gem "em-http-request"
gem "em-websocket", '~>0.5.1'
gem 'sidekiq'
gem 'rack'
gem 'colorize'

group :test, :development do
  gem 'rspec'
end

group :test do
  gem 'rack-test'
end
